# Generated by Django 3.2.11 on 2022-02-07 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sendTime', models.CharField(max_length=255)),
                ('senderUserID', models.CharField(max_length=255)),
                ('reciverUserID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4'), ('E', '5'), ('F', '6'), ('G', '7')], default='A', max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('reportedUserID', models.CharField(max_length=255, null=True)),
                ('reportingUserID', models.CharField(max_length=255, null=True)),
                ('responsibleCircleID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('circleID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('localization', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expireDate', models.DateTimeField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('maxUsers', models.IntegerField()),
                ('reportsID', models.CharField(max_length=255)),
                ('usersID', models.CharField(max_length=255)),
                ('stats', models.CharField(max_length=255)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
