# Generated by Django 3.2.11 on 2022-02-18 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciver_ID',
        ),
        migrations.AlterField(
            model_name='activesession',
            name='member1_ID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member1_ID', to='api.waitingroom', to_field='user_that_want_to_join_ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_ID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='user_that_want_to_join_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
